#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
gambitToFoam mesh.neu
cp -f constant/polyMesh/boundary.org constant/polyMesh/boundary
VOFSetFields

#-- Run on single processor
pyroFoam


# ----------------------------------------------------------------- end-of-file
