#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
runApplication blockMesh
runApplication VOFSetFields

#-- Decompose and run in parallel
#pyroFoam
runApplication decomposePar
mpirun -n 4 pyroFoam -parallel
#runParallel `getApplication` 4
#if this uses foamJob, then all the cases can be run at once

# ----------------------------------------------------------------- end-of-file
