#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
blockMesh
VOFSetFields
initDynamicMesh
cp 0.org/* 1e-06/
rm 1e-06/alphaGas
VOFSetFields
initDynamicMesh
cp 0.org/* 2e-06/
rm 2e-06/alphaGas
VOFSetFields

#-- Run on single processor
pyroFoam


# ----------------------------------------------------------------- end-of-file
