#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions


# code based on the Allrun for multiphase/interFoam/laminar


setMeshSize ()
{
    blockMeshDict="constant/polyMesh/blockMeshDict"
    controlDict="system/controlDict"
    VOFSetFields="system/VOFSetFieldsDict"
    U0="0.org/U"
    
    sed \
    -e s/"90 150 1"/"$1 $2 1"/g \
    $blockMeshDict > temp.$$
    
    mv temp.$$ $blockMeshDict
    
    sed \
    -e s/"\(endTime[ \t]*\) 2.0;"/"\1 $3;"/g \
    -e s/"\(flowRelaxTime[ \t]*\) 0.5;"/"\1 $4;"/g \
    -e s/"\(deltaT[ \t]*\) 1e-5;"/"\1 $5;"/g \
    $controlDict > temp.$$
    
    mv temp.$$ $controlDict
    
    sed \
    -e s/"0 10 0"/"0 $6 0"/g \
    $VOFSetFields > temp.$$
    
    mv temp.$$ $VOFSetFields
    
    sed \
    -e s/"0 10 0"/"0 $6 0"/g \
    $U0 > temp.$$
    
    mv temp.$$ $U0
    
}

# Set up case 1
cp -r testHTbase testHT1

(
    cd testHT1 || exit

    # Execute
    ./Allrun
    
    mv processor0/TsAvg.out ../TsAvg1.out
)

# Set up case 2
cp -r testHTbase testHT2

(
    cd testHT2 || exit

    # Modify case (nx ny endT relaxT dT U)
    setMeshSize 135 225 1.2 0.2 1e-6 10

    # And execute
    ./Allrun
    
    mv processor0/TsAvg.out ../TsAvg2.out
)

# Set up case 3
cp -r testHTbase testHT3

(
    cd testHT3 || exit

    # Modify case (nx ny endT relaxT dT U)
    setMeshSize 180 300 1.2 0.2 1e-6 10

    # And execute
    ./Allrun
    
    mv processor0/TsAvg.out ../TsAvg3.out
)

# Set up case 4
cp -r testHTbase testHT4

(
    cd testHT4 || exit

    # Modify case (nx ny endT relaxT dT U)
    setMeshSize 225 375 1.2 0.2 1e-6 10

    # And execute
    ./Allrun
    
    mv processor0/TsAvg.out ../TsAvg4.out
)

