#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
find . -name '*~' -delete
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0
rm -rf constant/gas/polyMesh
rm -rf constant/cylinder/polyMesh
rm -rf constant/polyMesh/boundary
rm -rf constant/cellToRegion.gz

# ----------------------------------------------------------------- end-of-file
