#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.org 0
#gambit -inp gambit_journal.jou
#rm -f default_id.*
gambitToFoam mesh.neu

stitchMesh Interior1A Interior1B -overwrite -perfect

topoSet

splitMeshRegions -cellZones -overwrite

rm -f 0/meshPhi*

# remove fluid fields from solid regions (important for post-processing)
for i in cylinder
do
   rm -f 0*/$i/{p*,U*}
done

for i in gas cylinder
do
   changeDictionary -region $i
done




#-- Run on single processor
#chtMultiRegionFoam

#exit
# run in parallel

# Decompose
for i in gas cylinder
do
   decomposePar -region $i
done

# Run
#runParallel `getApplication` 4
#exit
mpirun -np 4 chtMultiRegionFoam -parallel
#foamJob -screen -parallel chtMultiRegionFoam

# Reconstruct
for i in gas cylinder
do
   reconstructPar -region $i
done
sample -region gas

echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
