#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r 0.flow 0
blockMesh
VOFSetFields

# initDynamicMesh
# cp 0.org/* 9.9990001e-07/
# rm 9.9990001e-07/alphaGas
# VOFSetFields
# initDynamicMesh
# cp 0.org/* 1.9998e-06/
# rm 1.9998e-06/alphaGas
# VOFSetFields

#-- Run on single processor
pyroFoam

#-- Run on 6 processors
#decomposePar

#touch processor0/pyro.foam
#touch processor1/pyro.foam
#touch processor2/pyro.foam
#touch processor3/pyro.foam
#touch processor4/pyro.foam
#touch processor5/pyro.foam

#mpirun -np 6 pyroFoam -parallel

# ----------------------------------------------------------------- end-of-file
