#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso ../utilities/geometryTools
wmake libso ../utilities/immersedBoundary
wmake ../utilities/VOFSetFields
wmake ../utilities/initDynamicMesh
wmake libso burningSolid
wmake

# ----------------------------------------------------------------- end-of-file
