#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean
wclean burningSolid
wclean geometryTools
find . -name '*~' -delete

# ----------------------------------------------------------------- end-of-file
