#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean
wclean burningSolid
find . -name '*~' -delete

wclean ../utilities/immersedBoundary
wclean ../utilities/geometryTools
wclean ../utilities/initDynamicMesh
wclean ../utilities/VOFSetFields
# ----------------------------------------------------------------- end-of-file
